## MySQL
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sales_inventery
    username: root
    password: root
    initialization-mode: always
  jpa:
    hibernate:
      use-new-id-generator-mappings: false
      ddl-auto: none
      show-sql: true

# drop n create table, good for testing, comment this in production
#ddl-auto ==> create-drop, create-update

server:
  port: 8080

